### ISSUE TITLE
Should include fixes for identity projects, too

### ISSUE THREAD

**Issue by amoraitis** [ASHWINI-GUPTA/Bootstrap4#1]
A bit of an enhancement is to include the fixes should be made, when the asp.net core mvc project includes Identity.

**Comment by amoraitis** [comment]
I resolved this [in my article, here](http://amoraitis.me/net-core/2018/11/05/bootstrap4-in-aspnet-core-mvc-identity.html). The source code is avalaible [here](https://github.com/amoraitis/Bootstrap4Identity).

**Comment by ASHWINI-GUPTA** [comment]
Cool..! 👌
